### ISSUE TITLE
urlopen error [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ghost** [rcorcs/NatI#11]
/usr/lib/python2.7/urllib2.pyc in https_open(self, req)
   1220 
   1221         def https_open(self, req):
-> 1222             return self.do_open(httplib.HTTPSConnection, req)
   1223 
   1224         https_request = AbstractHTTPHandler.do_request_

/usr/lib/python2.7/urllib2.pyc in do_open(self, http_class, req)
   1182         except socket.error, err: # XXX what error?
   1183             h.close()
-> 1184             raise URLError(err)
   1185         else:
   1186             try:

URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by beyondszine** [comment]
I have similar urllib error:
`Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import commands
  File "/home/beyond/github/NatI/commands.py", line 18, in <module>
    songClient.init()
  File "/home/beyond/.local/lib/python2.7/site-packages/grooveshark/__init__.py", line 186, in init
    self.connection.init()
  File "/home/beyond/.local/lib/python2.7/site-packages/grooveshark/__init__.py", line 115, in init
    return self.init_token(), self.init_queue()
  File "/home/beyond/.local/lib/python2.7/site-packages/grooveshark/__init__.py", line 121, in init_token
    self._get_token()
  File "/home/beyond/.local/lib/python2.7/site-packages/grooveshark/__init__.py", line 99, in _get_token
    'client' : 'htmlshark'})[1]
  File "/home/beyond/.local/lib/python2.7/site-packages/grooveshark/__init__.py", line 136, in request
    with contextlib.closing(self.urlopen(request)) as response:
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name 
`
