### ISSUE TITLE
import pygst

### ISSUE THREAD

**Issue by fmoedas** [rcorcs/NatI#8]
File "main.py", line 11, in <module>
    import commands
  File "/home/pi/NatI-master/NatI-master/commands.py", line 10, in <module>
    import player
  File "/home/pi/NatI-master/NatI-master/player.py", line 1, in <module>
    import pygst
ImportError: No module named pygst

Alguém me pode ajudar? (Can you help me?)

**Comment by belinhacbr** [comment]
You need to install the pygst module. 
For Ubuntu/Debian:  
`sudo apt-get install python-gst0.10 gstreamer0.10-plugins-good gstreamer0.10-plugins-ugly`

**Comment by fmoedas** [comment]
It worked, but got this error now

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import commands
  File "/home/pi/NatI-master/NatI-master/commands.py", line 18, in <module>
    songClient.init()
  File "/usr/local/lib/python2.7/dist-packages/grooveshark/**init**.py", line 20                                                                                                             8, in init
    self.connection.init()
  File "/usr/local/lib/python2.7/dist-packages/grooveshark/**init**.py", line 12                                                                                                             8, in init
    return self.init_token(), self.init_queue()
  File "/usr/local/lib/python2.7/dist-packages/grooveshark/**init**.py", line 13                                                                                                             4, in init_token
    self._get_token()
  File "/usr/local/lib/python2.7/dist-packages/grooveshark/__init__.py", line 11                                                                                                             2, in _get_token
    'client': 'htmlshark'})[1]
  File "/usr/local/lib/python2.7/dist-packages/grooveshark/__init__.py", line 15                                                                                                             6, in request
    with contextlib.closing(self.urlopen(request)) as response:
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by erm3nda** [comment]
Can't be that packages be listed on the README?

**Comment by MuLx10** [comment]
facing the same problem

**Comment by rcorcs** [comment]
NatI used to be integrated with Grooveshark, which doesn't exist anymore.
I will remove from the code all Grooveshark dependencies.
